#define NK_IMPLEMENTATION
#define NK_INCLUDE_FONT_BAKING 
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_DEFAULT_FONT
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_STANDARD_VARARGS
#include "libs/nuklear.h"

#define STB_SPRINTF_IMPLEMENTATION
#include "libs/stb_sprintf.h"
#define STB_IMAGE_IMPLEMENTATION
#include "libs/stb_image.h"
